packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  typescript: ^5.3.3
  biome: ^1.5.3
  eslint: ^8.57.0
  vitest: ^1.3.1
  markuplint: ^3.15.0
  '@markuplint/jsx-parser': ^3.12.0
  '@markuplint/react-spec': ^3.12.0
  react: ^19.0.0
  'react-dom': ^19.0.0
  next: ^15.2.4
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@types/node': ^20.0.0
  tailwindcss: ^4.0.0
  postcss: ^8.0.0
  autoprefixer: ^10.0.0 